const CSS_PROPERTIES = {
    size: [
      "width",
      "min-width",
      "max-width",
      "height",
      "min-height",
      "max-height",
    ],
    margin: [
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
    ],
    padding: [
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
    ],
    border: [
      "border-width",
      "border-top-width",
      "border-right-width",
      "border-bottom-width",
      "border-left-width",
      "border-color",
      "border-style",
      "border-radius",
      "border-top-left-radius",
      "border-top-right-radius",
      "border-bottom-left-radius",
      "border-bottom-right-radius",
    ],
    background: [
      "background-color",
    ],
    typography: [
      "font-size",
      "line-height",
      "letter-spacing",
      "font-weight",
      "font-style",
      "text-align",
      "text-decoration-line",
      "color",
    ],
    display: [
      "display",
      "flex-direction",
      "flex-wrap",
      "justify-content",
      "align-items",
      "gap",
    ],
    position: [
      "position",
    ],
    boxShadow: [
      "box-shadow",
    ],
    opacity: [
      "opacity",
    ],
  };
const CSS_PROPERTIES_CAMEL_CASE = {
    size: [
      "width",
      "minWidth",
      "maxWidth",
      "height",
      "minHeight",
      "maxHeight",
    ],
    margin: [
      "marginTop",
      "marginRight",
      "marginBottom",
      "marginLeft",
    ],
    padding: [
      "paddingTop",
      "paddingRight",
      "paddingBottom",
      "paddingLeft",
    ],
    border: [
      "borderWidth",
      "borderTopWidth",
      "borderRightWidth",
      "borderBottomWidth",
      "borderLeftWidth",
      "borderColor",
      "borderStyle",
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    background: [
      "backgroundColor",
    ],
    typography: [
      "fontSize",
      "lineHeight",
      "letterSpacing",
      "fontWeight",
      "fontStyle",
      "textAlign",
      "textDecorationLine",
      "color",
    ],
    display: [
      "display",
      "flexDirection",
      "flexWrap",
      "justifyContent",
      "alignItems",
      "gap",
    ],
    position: [
      "position",
    ],
    boxShadow: [
      "boxShadow",
    ],
    opacity: [
      "opacity",
    ],
  };
const CSS_DEFAULT_VALUES_CAMEL_CASE = {
    "width": "auto",
    "minWidth": "0",
    "maxWidth": "none",
    "height": "auto",
    "minHeight": "0",
    "maxHeight": "none",
    "marginTop": "0",
    "marginRight": "0",
    "marginBottom": "0",
    "marginLeft": "0",
    "paddingTop": "0",
    "paddingRight": "0",
    "paddingBottom": "0",
    "paddingLeft": "0",
    "borderWidth": "medium",
    "borderTopWidth": "medium",
    "borderRightWidth": "medium",
    "borderBottomWidth": "medium",
    "borderLeftWidth": "medium",
    "borderColor": "currentcolor",
    "borderStyle": "none",
    "borderRadius": "0",
    "borderTopLeftRadius": "0",
    "borderTopRightRadius": "0",
    "borderBottomLeftRadius": "0",
    "borderBottomRightRadius": "0",
    "backgroundColor": "transparent",
    "fontSize": "medium",
    "lineHeight": "normal",
    "letterSpacing": "normal",
    "fontWeight": "400",
    "fontStyle": "normal",
    "textAlign": "start",
    "textDecorationLine": "none",
    "color": "initial",
    "display": "inline",
    "flexDirection": "row",
    "flexWrap": "nowrap",
    "justifyContent": "flex-start",
    "alignItems": "stretch",
    "gap": "0",
    "position": "static",
    "boxShadow": "none",
    "opacity": "1",
};

const CSS_DEFAULT_VALUES_HYPHEN = {
    "width": "auto",
    "min-width": "0",
    "max-width": "none",
    "height": "auto",
    "min-height": "0",
    "max-height": "none",
    "margin-top": "0",
    "margin-right": "0",
    "margin-bottom": "0",
    "margin-left": "0",
    "padding-top": "0",
    "padding-right": "0",
    "padding-bottom": "0",
    "padding-left": "0",
    "border-width": "medium",
    "border-top-width": "medium",
    "border-right-width": "medium",
    "border-bottom-width": "medium",
    "border-left-width": "medium",
    "border-color": "currentcolor",
    "border-style": "none",
    "border-radius": "0",
    "border-top-left-radius": "0",
    "border-top-right-radius": "0",
    "border-bottom-left-radius": "0",
    "border-bottom-right-radius": "0",
    "background-color": "transparent",
    "font-size": "medium",
    "line-height": "normal",
    "letter-spacing": "normal",
    "font-weight": "400",
    "font-style": "normal",
    "text-align": "start",
    "text-decoration-line": "none",
    "color": "initial",
    "display": "inline",
    "flex-direction": "row",
    "flex-wrap": "nowrap",
    "justify-content": "flex-start",
    "align-items": "stretch",
    "gap": "0",
    "position": "static",
    "box-shadow": "none",
    "opacity": "1",
};

const ALL_CSS_PROPERTIES_CAMEL_CASE = Object.values(CSS_DEFAULT_VALUES_CAMEL_CASE)
    .flat();
const ALL_CSS_PROPERTIES_HYPHEN = Object.keys(CSS_DEFAULT_VALUES_HYPHEN)
    .flat()
    // .map((prop) => prop.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase());
  